
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain dial_domain)
    (:requirements :equality)
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (have_order )
        (maybe-have_order )
        (have_location )
        (maybe-have_location )
        (have_payment_method )
        (maybe-have_payment_method )
        (have_card_number )
        (maybe-have_card_number )
        (can-do_ask-location )
        (can-do_ask-order )
        (can-do_ask-payment )
        (can-do_ask-card-number )
        (can-do_check-order-availability )
        (can-do_place-order )
    )

    (:functions
        
    )

    

    
)