name: check

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.12'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Linting
      run: |
        flake8 . --count --show-source --statistics --max-line-length=88